"""
AI Desktop Agent - Main Entry Point

This is the orchestrator that coordinates all modules in Phase 2.

ARCHITECTURE:
  User Input → LLM Interpreter → Policy Decision → Registry Validator → Safe Executor

SECURITY MODEL:
  - Phase 1 (bootstrap_scan.py) must be run FIRST to generate app_registry.json
  - Phase 2 (this file) NEVER scans the system
  - The LLM NEVER sees file paths or commands
  - The executor ONLY receives validated paths from the registry

FLOW:
  1. User provides natural language input
  2. LLM interprets input → structured goal
  3. Policy engine maps goal → app name
  4. Registry validates app name → executable path
  5. Executor launches validated path
"""

import sys
import json
import logging
from pathlib import Path
from typing import Optional, Dict

# Import all modules
from llm.interpreter import NaturalLanguageInterpreter
from policy.decision import PolicyDecisionEngine
from system.executor import SafeExecutor
from memory.state import AgentMemory
from ui.cli import CLI

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('agent.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)


class AIDesktopAgent:
    """
    Main AI Desktop Agent orchestrator.
    
    This class coordinates all modules and enforces the security architecture.
    It ensures that the LLM never sees paths, the executor never receives user input,
    and all decisions are validated against the registry.
    """
    
    # Minimum confidence threshold for LLM interpretations
    MIN_CONFIDENCE = 0.70
    
    def __init__(self, config_dir: Optional[Path] = None, dry_run: bool = False):
        """
        Initialize the AI Desktop Agent.
        
        Args:
            config_dir: Directory containing app_registry.json
            dry_run: If True, simulate execution without launching apps
        """
        # Determine config directory
        if config_dir is None:
            config_dir = Path(__file__).parent / 'config'
        
        self.config_dir = Path(config_dir)
        self.registry_path = self.config_dir / 'app_registry.json'
        self.memory_path = self.config_dir / 'memory.json'
        self.dry_run = dry_run
        
        # Initialize modules
        self.cli = CLI()
        self.interpreter = NaturalLanguageInterpreter()
        self.policy = PolicyDecisionEngine(registry_path=self.registry_path)
        self.executor = SafeExecutor(dry_run=dry_run)
        self.memory = AgentMemory(persist_path=self.memory_path)
        
        # Load registry
        self.registry: Dict[str, str] = {}
        self._load_registry()
        
        logger.info("AI Desktop Agent initialized")
    
    def _load_registry(self) -> None:
        """
        Load the application registry from disk.
        
        This registry was generated by Phase 1 (bootstrap_scan.py).
        The agent NEVER modifies this file at runtime.
        """
        if not self.registry_path.exists():
            logger.error(f"Registry not found: {self.registry_path}")
            self.cli.show_error("Application registry not found!")
            self.cli.show_warning("Please run bootstrap scan first:")
            self.cli.show_info("  python -m tools.bootstrap_scan")
            sys.exit(1)
        
        try:
            with open(self.registry_path, 'r', encoding='utf-8') as f:
                registry_data = json.load(f)
            
            self.registry = registry_data.get('applications', {})
            logger.info(f"Loaded {len(self.registry)} applications from registry")
            
        except Exception as e:
            logger.error(f"Failed to load registry: {e}")
            self.cli.show_error(f"Failed to load registry: {e}")
            sys.exit(1)
    
    def _validate_app_in_registry(self, app_name: str) -> Optional[str]:
        """
        Validate that an app exists in the registry and return its path.
        
        This is the ONLY place where app names are converted to paths.
        
        Args:
            app_name: Friendly app name (e.g., "notepad", "chrome")
            
        Returns:
            Executable path if app exists in registry, None otherwise
        """
        if app_name in self.registry:
            path = self.registry[app_name]
            logger.info(f"Registry validation: {app_name} → {path}")
            return path
        else:
            logger.warning(f"App '{app_name}' not found in registry")
            return None
    
    def _handle_special_command(self, user_input: str) -> bool:
        """
        Handle special commands (help, list, stats, exit).
        
        Args:
            user_input: User input string
            
        Returns:
            True if command was handled, False otherwise
        """
        command = user_input.lower().strip()
        
        if command in ['help', '?']:
            self.cli.show_help()
            return True
        
        elif command == 'list':
            self.cli.show_app_list(self.registry)
            return True
        
        elif command == 'stats':
            stats = self.memory.get_stats()
            self.cli.show_stats(stats)
            return True
        
        elif command == 'clear':
            if self.cli.confirm("Clear all memory?"):
                self.memory.clear()
                self.cli.show_success("Memory cleared")
            return True
        
        elif command in ['exit', 'quit', 'q']:
            return True
        
        return False
    
    def process_request(self, user_input: str) -> None:
        """
        Process a user request through the full pipeline.
        
        PIPELINE:
          1. LLM Interpreter: text → goal
          2. Policy Decision: goal → app_name
          3. Registry Validator: app_name → path
          4. Safe Executor: path → execution
          5. Memory: record observation
        
        Args:
            user_input: Raw natural language input from user
        """
        logger.info(f"Processing request: {user_input}")
        
        # Step 1: LLM Interpretation
        interpretation = self.interpreter.interpret(user_input)
        goal = interpretation.get('goal')
        confidence = interpretation.get('confidence', 0.0)
        reasoning = interpretation.get('reasoning', '')
        
        # Handle chat/conversational intents
        if goal == 'chat':
            chat_response = self.interpreter.generate_chat_response(user_input)
            self.cli.show_chat_response(chat_response)
            
            # Record chat interaction
            self.memory.record(user_input, goal, confidence, None, True, "Chat response")
            return
        
        self.cli.show_interpretation(goal, confidence, reasoning)
        
        # Validate confidence threshold
        if not self.interpreter.validate_interpretation(interpretation, self.MIN_CONFIDENCE):
            self.cli.show_error("Could not understand your request with sufficient confidence")
            self.cli.show_info("Try being more specific, e.g., 'open notepad' or 'launch chrome'")
            
            # Record failed attempt
            self.memory.record(user_input, goal, confidence, None, False, "Low confidence")
            return
        
        # Step 2: Policy Decision
        app_name = self.policy.decide(goal)
        
        if not app_name:
            self.cli.show_error("Could not determine which application to launch")
            self.cli.show_info("Type 'list' to see available applications")
            
            # Record failed attempt
            self.memory.record(user_input, goal, confidence, None, False, "No policy mapping")
            return
        
        logger.info(f"Policy decision: {goal} → {app_name}")
        
        # Step 3: Registry Validation
        executable_path = self._validate_app_in_registry(app_name)
        
        if not executable_path:
            self.cli.show_error(f"Application '{app_name}' not found in registry")
            self.cli.show_info("The application may not be installed or may need to be added to the registry")
            
            # Record failed attempt
            self.memory.record(user_input, goal, confidence, app_name, False, "Not in registry")
            return
        
        # Step 4: Safe Execution
        result = self.executor.execute(executable_path)
        
        # Display result
        if result['success']:
            self.cli.show_success(result['message'])
        else:
            self.cli.show_error(result['message'])
        
        # Step 5: Record observation
        self.memory.record(
            user_input=user_input,
            goal=goal,
            confidence=confidence,
            app_name=app_name,
            success=result['success'],
            message=result['message']
        )
    
    def run(self) -> None:
        """
        Main agent loop.
        
        This method runs the interactive agent session.
        """
        # Show banner
        self.cli.show_banner()
        
        if self.dry_run:
            self.cli.show_warning("Running in DRY RUN mode - no apps will be launched")
        
        self.cli.show_info(f"Loaded {len(self.registry)} applications")
        self.cli.show_info("Type 'help' for commands or describe what you want to do")
        
        # Main loop
        while True:
            try:
                # Get user input
                user_input = self.cli.prompt_input()
                
                # Check for empty input
                if not user_input:
                    continue
                
                # Check for exit
                if user_input.lower() in ['exit', 'quit', 'q']:
                    break
                
                # Handle special commands
                if self._handle_special_command(user_input):
                    if user_input.lower() in ['exit', 'quit', 'q']:
                        break
                    continue
                
                # Process normal request
                self.process_request(user_input)
                
            except KeyboardInterrupt:
                print("\n")
                break
            except Exception as e:
                logger.error(f"Unexpected error: {e}", exc_info=True)
                self.cli.show_error(f"An error occurred: {e}")
        
        # Show goodbye
        self.cli.show_goodbye()
        
        # Show final stats
        stats = self.memory.get_stats()
        if stats['total_interactions'] > 0:
            self.cli.show_stats(stats)


def main():
    """Main entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(description='AI Desktop Agent - Security-First Edition')
    parser.add_argument('--dry-run', action='store_true', help='Simulate execution without launching apps')
    parser.add_argument('--config-dir', type=Path, help='Path to config directory')
    
    args = parser.parse_args()
    
    # Create and run agent
    agent = AIDesktopAgent(config_dir=args.config_dir, dry_run=args.dry_run)
    agent.run()


if __name__ == '__main__':
    main()
